# roles/namespace/tasks/main.yml
---
- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: Install package for Erasure Code
  package:
    name: "{{ 'libisal' if ansible_os_family == 'RedHat' else 'libisal2' }}"
    state: present
  when:
    - openio_namespace_storage_policy | map('lower') | select('match', 'ecisal') | list
    - ansible_architecture == 'x86_64'
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages_isal
  until: install_packages_isal is success
  retries: 5
  delay: 2

- name: Test directories presence
  stat:
    path: "{{ item }}"
  register: _dir
  with_items:
    - "/etc/oio/sds.conf.d"
  tags: install

- name: Test namespace file
  stat:
    path: "/etc/oio/sds.conf.d/{{ openio_namespace_name }}"
  register: _ns
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.item }}"
    state: directory
    owner: openio
    group: openio
    mode: 0755
    recurse: true
  with_items: "{{ _dir.results }}"
  when: not item.stat.exists
  tags: install

- name: Generate configuration files
  template:
    src: "namespace.j2"
    dest: "/etc/oio/sds.conf.d/{{ openio_namespace_name }}"
    owner: openio
    group: openio
    mode: 0644
  when: not _ns.stat.exists or openio_namespace_overwrite
...
