# roles/namespace/tasks/main.yml
---
- name: Install package for Erasure Code
  package:
    name: "{{ 'libisal' if ansible_os_family == 'RedHat' else 'libisal2' }}"
    state: present
  when: ansible_architecture == 'x86_64'
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages_isal
  until: install_packages_isal is success
  retries: 5
  delay: 2
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/oio/sds.conf.d"
  tags: configure

- name: Generate configuration files
  template:
    src: "namespace.j2"
    dest: "/etc/oio/sds.conf.d/{{ openio_namespace_name }}"
    owner: openio
    group: openio
    mode: 0644
    force: "{{ openio_namespace_overwrite }}"
  register: _ns
  tags: configure

- name: restart oioproxy
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart {{ openio_namespace_name }}-oioproxy-{{ 0 + openio_legacy_serviceid | d(0) | int }}
  when:
    - _ns.changed
    - not openio_namespace_provision_only
  register: _restart_oioproxy
  failed_when:
    - _restart_oioproxy.rc != 0
    # resource oioproxy not found
    - not 'No such file or directory' in _restart_oioproxy.stdout
    # gridinit not found
    - not 'not found' in _restart_oioproxy.stderr
  tags: configure
...
